name: env-dev.yml
on:
  pull_request:
    paths:
      - 'env-dev.yml'
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Env Valid
        uses: mamba-org/setup-micromamba@f8b8a1e23a26f60a44c853292711bacfd3eac822 #v1.9.0
        with:
          micromamba-version: '1.5.8-0'
          environment-file: env-dev.yml
          environment-name: test-access-ram-environment-dev
          generate-run-shell: false