name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'env.yml'
  pull_request: #TODO: remove this line after testing
  workflow_dispatch: #TODO: remove this line after testing

jobs:
  setup-deployment-env:
    name: Setup Deployment Environment
    runs-on: ubuntu-latest
    outputs:
      deployment-environments: ${{ steps.get-deployment-environment.outputs.deployment-environments }}
    steps:
      - name: Checkout config
        uses: actions/checkout@v4

      - name: Get environments
        id: get-deployment-environment
        run: echo "deployment-environments=$(jq --compact-output '.environments' ./config/deployment-environment.json)" >> $GITHUB_OUTPUT

  pack:
    name: Pack access-ram-env
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.access-ram.outputs.name }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Payu Version
        id: access-ram
        run: echo "name=$(yq '.name' < env.yml)" >> $GITHUB_OUTPUT

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@f8b8a1e23a26f60a44c853292711bacfd3eac822 #v1.9.0
        with:
          micromamba-version: '1.5.8-0'
          environment-file: env.yml
          environment-name: ${{ steps.access-ram.outputs.name }}
          generate-run-shell: true

      - name: Create Pack and Lockfile
        shell: micromamba-shell {0}
        run: |
          conda pack
          # conda-lock lock --file env.yml --platform linux-64 --micromamba --lockfile ${{ steps.access-ram.outputs.name }}.conda-lock.yml
      # TODO: Solve issue with conda-lock (https://github.com/ACCESS-NRI/access-ram-condaenv/issues/3)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.access-ram.outputs.name }}
          if-no-files-found: error
          path: |
            ${{ steps.access-ram.outputs.name }}.tar.gz
            # ${{ steps.access-ram.outputs.name }}.conda-lock.yml
      # TODO: Solve issue with conda-lock (https://github.com/ACCESS-NRI/access-ram-condaenv/issues/3)

  deploy:
    runs-on: ubuntu-latest
    needs:
      - pack
      - setup-deployment-env
    strategy:
      fail-fast: false
      matrix:
        deployment-environment: ${{ fromJson(needs.setup-deployment-env.outputs.deployment-environments) }}
    environment: ${{ matrix.deployment-environment }}
    env:
      NAME: ${{ needs.pack.outputs.name }}
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.NAME }}
      
      - name: Set up SSH
        uses: access-nri/actions/.github/actions/setup-ssh@main
        id: ssh
        with:
          hosts: |
            ${{ secrets.HOST_DATA }}
            ${{ secrets.HOST }}
          private-key: ${{ secrets.SSH_KEY }}

      - name: Copy to ${{ matrix.deployment-environment }}
        run: |
          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            ${{ env.NAME }}.tar.gz \
            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ vars.DEPLOYMENT_LOCATION }}

      - name: Deploy to ${{ matrix.deployment-environment }}
        env:
          ENVIRONMENT_LOCATION: ${{ vars.DEPLOYMENT_LOCATION }}
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          mkdir -p ${{ env.ENVIRONMENT_LOCATION }}
          if [ $? -ne 0 ]; then
            exit $?
          fi
          tar -xzf ${{ vars.DEPLOYMENT_LOCATION }}/${{ env.NAME }}.tar.gz -C ${{ env.ENVIRONMENT_LOCATION }}
          source ${{ env.ENVIRONMENT_LOCATION }}/bin/activate
          conda-unpack
          source ${{ env.ENVIRONMENT_LOCATION }}/bin/deactivate
          # ln -s ${{ vars.MODULE_LOCATION }}/.common ${{ vars.MODULE_LOCATION }}/${{ env.VERSION }}
          EOT

      # Release
      # - name: Create Release
      #   uses: softprops/action-gh-release@v0.1.15
      #   with:
      #     tag_name: ${{ env.VERSION }}
      #     name: Payu ${{ env.VERSION }}
      #     generate_release_notes: true
      #     fail_on_unmatched_files: true
      #     files: |
      #       ./${{ env.NAME }}.tar.gz
      #       # ./${{ env.NAME }}.conda-lock.yml
      # # TODO: Solve issue with conda-lock (https://github.com/ACCESS-NRI/access-ram-condaenv/issues/3)