name: Update common modulefiles on Gadi
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'modules/**'
jobs:
  setup-deployment-env:
    name: Setup Deployment Environment
    runs-on: ubuntu-latest
    outputs:
      deployment-environments: ${{ steps.get-deployment-environment.outputs.deployment-environments }}
    steps:
      - name: Checkout config
        uses: actions/checkout@v4

      - name: Get environments
        id: get-deployment-environment
        run: echo "deployment-environments=$(jq --compact-output '.environments' ./config/deployment-environment.json)" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: setup-deployment-env
    strategy:
      fail-fast: false
      matrix:
        deployment-environment: ${{ fromJson(needs.setup-deployment-env.outputs.deployment-environments) }}
    environment: ${{ matrix.deployment-environment }}
    steps:
      - uses: actions/checkout@v4

      - uses: access-nri/actions/.github/actions/setup-ssh@main
        id: ssh
        with:
          hosts: |
            ${{ secrets.HOST_DATA }}
          private-key: ${{ secrets.SSH_KEY }}

      - name: Generate release modulesfiles
        run: |
          mkdir -p release/modules
          sed 's|{{MODULE_DIR}}|'"${{ vars.MODULE_DIR }}"'|g' modules/.common > release/modules/.common
          sed 's|{{APPS_DIR}}|'"${{ vars.APPS_DIR }}"'|g' modules/env.sh > release/modules/env.sh
          chmod +x release/modules/env.sh

    #   - name: Generate pre-release modulesfiles
    #     run: |
    #       mkdir -p prerelease/modules
    #       sed 's|{{MODULE_LOCATION}}|'"${{ vars.PRERELEASE_MODULE_LOCATION }}"'|g' modules/.common > prerelease/modules/.common
    #       sed 's|{{ENVIRONMENT_LOCATION}}|'"${{ vars.PRERELEASE_ENVIRONMENT_LOCATION }}"'|g' modules/env.sh > prerelease/modules/env.sh
    #       chmod +x prerelease/modules/env.sh

      - name: Create deployment directory on ${{ matrix.deployment-environment }}
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST_DATA }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          mkdir -p ${{ vars.MODULE_DIR }}
          EOT

      - name: Copy modulefiles to Gadi
        run: |
          # Rsync release modulefiles
          rsync -rvp -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            release/modules/ \
            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ vars.MODULE_DIR }}

        #   # Rsync development modulefiles
        #   rsync -rvp -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
        #     prerelease/modules/ \
        #     ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ vars.PRERELEASE_MODULE_LOCATION }}